### ISSUE TITLE
messages failing (keep open to enrich during testing)

### ISSUE THREAD

**Issue by jmaupoux** [exanpe/universal-breakfast#52]
account/index : ub.register.password.label

manage/index : when no user are found, message color should be white

**Comment by splanard** [comment]
failing messages at /account/index :
ub.register.password.label
ub.register.confirm.password.label
![fail_messages](https://cloud.githubusercontent.com/assets/8502688/10185846/68d8b80c-674c-11e5-949b-f7eb3d488096.jpg)
