### ISSUE TITLE
Equipe de petit déjeuner

### ISSUE THREAD

**Issue by rildo** [exanpe/universal-breakfast#57]
Hello,
Is it possible to add a variable for email to include those who are in charge of breakfast.
We can already chose several providers fut for a practical reason, it is interesting that these people know each other.

**Comment by jmaupoux** [comment]
deployed

**Comment by rildo** [comment]
Thanks !
Is this feature available for the gathering ?
The documentation indicates that this feature is available for the mail preparation but not for the gathering.

**Comment by jmaupoux** [comment]
Hi
No it's not available on gathering, we didn't find a real need in that mail.

**Comment by jmaupoux** [comment]
Implementation has been deployed in gathering mail
