### ISSUE TITLE
missing users

### ISSUE THREAD

**Issue by rildo** [exanpe/universal-breakfast#61]
We finalised some breakfast and until then, the preparators are no longer proposed in the handlers list.
6 users disappeared.

**Comment by jmaupoux** [comment]
Could you tell me more about the users ? Have they been "deleted" from team ??

**Comment by rildo** [comment]
No, they're still in the finalize list. They just vanished from the preparation list.

I tried to delete and recreate those users but the bug persist.

**Comment by rildo** [comment]
The preparation list display how many users ?

**Comment by jmaupoux** [comment]
Preparation list currently displays top 10 users according to app's algorithm
I understand that's a limitation for your team ?

**Comment by rildo** [comment]
No but maybe this information should be displayed. Personally I thought it was a bug.
