### ISSUE TITLE
Suppliers list in e-mail

### ISSUE THREAD

**Issue by rildo** [exanpe/universal-breakfast#62]
The suppliers name in the e-mail are not working. It leaves a blank instead of showing the suppliers name.
![sans titre](https://cloud.githubusercontent.com/assets/679059/22820634/efe90d9c-ef77-11e6-97ec-7bbba0a58c27.png)

**Comment by jmaupoux** [comment]
I cannot reproduce, it works as expected on my test account.

Can you send me your mail template ?

**Comment by rildo** [comment]
> Salut,<br/>
> <br/>
> L'équipe _TEAM_NAME_ ( _SUPPLIERS_ ) t'attend à la salle de pause pour le petit déjeuner !<br/>
> <br />
> "Bon Appétit!"<br/>
> Note : _MESSAGE_

**Comment by jmaupoux** [comment]
Could you tell me if the bug is still present ?

**Comment by rildo** [comment]
Yes, it still happens.
