### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by rildo** [exanpe/universal-breakfast#64]
The website seems down :

![capture](https://user-images.githubusercontent.com/679059/33475698-a8257f1e-d67f-11e7-9cd3-c6f15df2e989.JPG)

**Comment by lguerin** [comment]
Hello,
the demo website have been moved to Openshift virtual machines, sometime the VM may be down, you need to refresh few seconds after the first call:
http://grails-exanpe-grails-exanpe.193b.starter-ca-central-1.openshiftapps.com/exaDatatablesDemo/index
